# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AuthingAws < Formula
  desc "Fetching your AWS Access token via Authing"
  homepage "https://github.com/dreampuf/authing-aws"
  version "0.0.1"
  license "GPL-3.0 license"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dreampuf/authing-aws/releases/download/v0.0.1/authing-aws_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "178badf0e723cd09988942beae534eaea940dc5fb4b6caf5bf167f932c1a8352"

      def install
        bin.install "authing-aws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dreampuf/authing-aws/releases/download/v0.0.1/authing-aws_0.0.1_Darwin_arm64.tar.gz"
      sha256 "202627c9cf79a115916a414e91fe3ff8100a65a8140a1578737d8d7cb1506cbc"

      def install
        bin.install "authing-aws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dreampuf/authing-aws/releases/download/v0.0.1/authing-aws_0.0.1_Linux_x86_64.tar.gz"
      sha256 "eecfd176802d3772bb50b95648c21ddf8ee5b88539c61ec885dc860ca7f936b2"

      def install
        bin.install "authing-aws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dreampuf/authing-aws/releases/download/v0.0.1/authing-aws_0.0.1_Linux_arm64.tar.gz"
      sha256 "e22681536d21cc7513bf8f4b92a804355d22a2c75cd7de5e40488a27bc55f059"

      def install
        bin.install "authing-aws"
      end
    end
  end

  test do
    system "#{bin}/program", "version"
  end
end
